from Parameters import *
import numpy as np
import matplotlib.pyplot as plt

for particle_index in range(PARTICLE_NUMBER):
    z, gen_t, gen_x, gen_y, gen_v, gen_xz, gen_yz, pre_t, pre_st, pre_x, pre_sx, pre_y, pre_sy, pre_v, pre_sv, pre_xz, pre_sxz, pre_yz, pre_syz, fil_t, fil_st, fil_x, fil_sx, fil_y, fil_sy,fil_v, fil_sv, fil_xz, fil_sxz, fil_yz, fil_syz, smo_t, smo_st, smo_x, smo_sx, smo_y, smo_sy, smo_v, smo_sv, smo_xz, smo_sxz, smo_yz, smo_syz = np.loadtxt(f"../data/Particle {particle_index}.csv", skiprows=2, unpack=True, delimiter=",", dtype=float)

    figure_t, ax_t = plt.subplots()
    ax_t.grid()
    ax_t.set_xlabel("Z [m]")
    ax_t.set_ylabel("t [s]")
    t_max = np.max(np.abs(gen_t))
    ax_t.set_ylim([-t_max*1.5,t_max*1.8])
    ax_t.errorbar(z, gen_t, ls=" ", fmt="o", elinewidth=1, capsize=2, label="generated", color="black")
    # ax_t.errorbar(z, pre_t, yerr=pre_st, ls=" ", fmt="o", elinewidth=1, capsize=2, label="predicted", color="red")
    ax_t.errorbar(z, fil_t, yerr=fil_st, ls=" ", fmt="o", elinewidth=1, capsize=2, label="filtered", color="blue")
    # ax_t.errorbar(z, smo_t, yerr=smo_st, ls=" ", fmt="o", elinewidth=1, capsize=2, label="smoothed", color="green")
    ax_t.legend()
    figure_t.savefig(f"Particle {particle_index} t.pdf")
    plt.close(figure_t)

    figure_x, ax_x = plt.subplots()
    ax_x.grid()
    ax_x.set_xlabel("Z [m]")
    ax_x.set_ylabel("x [m]")
    x_max = np.max(np.abs(gen_x))
    ax_x.set_ylim([-x_max*1.5,x_max*1.8])
    ax_x.errorbar(z, gen_x, ls=" ", fmt="o", elinewidth=1, capsize=2, label="generated", color="black")
    ax_x.errorbar(z, pre_x, yerr=pre_sx, ls=" ", fmt="o", elinewidth=1, capsize=2, label="predicted", color="red")
    ax_x.errorbar(z, fil_x, yerr=fil_sx, ls=" ", fmt="o", elinewidth=1, capsize=2, label="filtered", color="blue")
    ax_x.errorbar(z, smo_x, yerr=smo_sx, ls=" ", fmt="o", elinewidth=1, capsize=2, label="smoothed", color="green")
    ax_x.legend()
    figure_x.savefig(f"Particle {particle_index} x.pdf")
    plt.close(figure_x)

    figure_y, ax_y = plt.subplots()
    ax_y.grid()
    ax_y.set_xlabel("Z [m]")
    ax_y.set_ylabel("y [m]")
    ax_y.errorbar(z, gen_y, ls=" ", fmt="o", elinewidth=1, capsize=2, label="generated", color="black")
    ax_y.errorbar(z, pre_y, yerr=pre_sy, ls=" ", fmt="o", elinewidth=1, capsize=2, label="predicted", color="red")
    ax_y.errorbar(z, fil_y, yerr=fil_sy, ls=" ", fmt="o", elinewidth=1, capsize=2, label="filtered", color="blue")
    ax_y.errorbar(z, smo_y, yerr=smo_sy, ls=" ", fmt="o", elinewidth=1, capsize=2, label="smoothed", color="green")
    ax_y.legend()
    figure_y.savefig(f"Particle {particle_index} y.pdf")
    plt.close(figure_y)

    figure_v, ax_v = plt.subplots()
    ax_v.grid()
    ax_v.set_xlabel("Z [m]")
    ax_v.set_ylabel("v [m/s]")
    ax_v.errorbar(z, gen_v, ls=" ", fmt="o", elinewidth=1, capsize=2, label="generated", color="black")
    ax_v.errorbar(z, pre_v, yerr=pre_sv, ls=" ", fmt="o", elinewidth=1, capsize=2, label="predicted", color="red")
    ax_v.errorbar(z, fil_v, yerr=fil_sv, ls=" ", fmt="o", elinewidth=1, capsize=2, label="filtered", color="blue")
    ax_v.errorbar(z, smo_v, yerr=smo_sv, ls=" ", fmt="o", elinewidth=1, capsize=2, label="smoothed", color="green")
    ax_v.legend()
    figure_v.savefig(f"Particle {particle_index} v.pdf")
    plt.close(figure_v)

    figure_xz, ax_xz = plt.subplots()
    ax_xz.grid()
    ax_xz.set_xlabel("Z [m]")
    ax_xz.set_ylabel("xz [s]")
    ax_xz.errorbar(z, gen_xz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="generated", color="black")
    ax_xz.errorbar(z, pre_xz, yerr=pre_sxz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="predicted", color="red")
    ax_xz.errorbar(z, fil_xz, yerr=fil_sxz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="filtered", color="blue")
    ax_xz.errorbar(z, smo_xz, yerr=smo_sxz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="smoothed", color="green")
    ax_xz.legend()
    figure_xz.savefig(f"Particle {particle_index} xz.pdf")
    plt.close(figure_xz)

    figure_yz, ax_yz = plt.subplots()
    ax_yz.grid()
    ax_yz.set_xlabel("Z [m]")
    ax_yz.set_ylabel("yz []")
    ax_yz.errorbar(z, gen_yz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="generated", color="black")
    ax_yz.errorbar(z, pre_yz, yerr=pre_syz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="predicted", color="red")
    ax_yz.errorbar(z, fil_yz, yerr=fil_syz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="filtered", color="blue")
    ax_yz.errorbar(z, smo_yz, yerr=smo_syz, ls=" ", fmt="o", elinewidth=1, capsize=2, label="smoothed", color="green")
    ax_yz.legend()
    figure_yz.savefig(f"Particle {particle_index} yz.pdf")
    plt.close(figure_yz)
