PARTICLE_NUMBER = 1

FOUNDAMENTAL_CHARGE = 1.602176634e-19;
LIGHT_SPEED = 299792458.;

MIN_PARTICLE_MASS = (0.5e6 * FOUNDAMENTAL_CHARGE) / (LIGHT_SPEED * LIGHT_SPEED);
MAX_PARTICLE_MASS = (300e6 * FOUNDAMENTAL_CHARGE) / (LIGHT_SPEED * LIGHT_SPEED);

MIN_BETA = 0.8;
MAX_BETA = 1.;

NUMBER_OF_DETECTORS = 6;
DISTANCE_BETWEEN_DETECTORS = 5e-3;
DETECTOR_DIMENSION = 1.;
DETECTOR_SPACE_UNCERTAINTY = 1e-6;
DETECTOR_TIME_UNCERTAINTY = 1e-11;
