#pragma once

#include <TLorentzVector.h>
#include <vector>

/**
 * The speed of light in international system of measurements.
 */
constexpr double LIGHT_SPEED_IS = 299792458.;


/**
 * The particle class.
 *
 * It represents a single particle generated by the particle gun.
 * It has a vector containing all the positions reached by the simulation.
 */
class Particle {
public:
    Particle(TLorentzVector initialPosition, TLorentzVector momentum, double charge=0.);

    TLorentzVector zSpaceEvolve(double finalZ);
    TLorentzVector timeEvolve(double timeStep);

    std::vector<TLorentzVector> getPositions() { return positions; }
    TLorentzVector getMomentum() { return momentum; }

private:
    TLorentzVector momentum;
    std::vector<TLorentzVector> positions;

    const double charge;
    const double mass;
};
